### PR TITLE
(HI-304) Add behavioral test

### PR DESCRIPTION
**Pull request by MikaelSmith**
Adds a behavioral test for interpolation with order
override to confirm/demonstrate the fixed behavior.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
ping @er0ck

**Comment by er0ck** [comment]
looks good so far!  have to head out of the office.   don't merge this until the fixes are merged...

**Comment by MikaelSmith** [comment]
Which fixes are pending?

**Comment by er0ck** [comment]
strange.  when i looked at PR-224 i could have sworn it wasn't merged.  now it says 7 days ago.  (shrug)
will try this out in the am...

**Pull request merged**
