### PR TITLE
(HI-483) Use compaitibility mode from deep_merge as default

### PR DESCRIPTION
**Pull request by Mike-Petersen**
With this commit you can use hiera and active support in the same project.

See discussion in previous pull request https://github.com/puppetlabs/hiera/pull/324

### CODE REVIEW

**Comment by MikaelSmith** [comment]
`rails_compat` seems to be part of deep_merge. That's pretty terrible.

@hlindberg does this seem reasonable, or did you have another approach in mind?

**Comment by hlindberg** [comment]
I am fine with this approach as long as it is 100% the same as doing the non compat, and that it does not clash with puppet and hiera being used together. I hope that reference to "rails" in the require does not imply in any way that anything "rails" related must be present.

**Comment by MikaelSmith** [comment]
It requires https://github.com/danielsdeleo/deep_merge/blob/master/lib/deep_merge/rails_compat.rb, which doesn't require anything except `deep_merge/core`.

**Comment by hlindberg** [comment]
Thanks @MikaelSmith that looks fine - poor choice on  naming the feature something with "rails" although I understand why.

**Pull request merged**
