### PR TITLE
(HI-464)  Add beaker node defs for Win10(x86,x64)

### PR DESCRIPTION
**Pull request by johnduarte**
[skip-ci]

### CODE REVIEW

**Comment by whopper** [comment]
@johnduarte we think this needs a rebase to make the travis commit test pass.

**Comment by johnduarte** [comment]
thanks @whopper . rebased and waiting for another travis run.

**Comment by whopper** [comment]
Hm, that didn't work. So Travis is mad because of those duplicate merges in master/stable of the ubuntu node def removal with the `(PUP-...)` tag. Any PR against stable is going to fail on that check now. We're going to need to do something about that to get it out of the git history :( /cc @kylog 

(We'll have the same problem for facter)

**Comment by whopper** [comment]
Note: needs a merge up to master when merged.

**Comment by kylog** [comment]
Merged up to master too.

**Pull request merged**
