### PR TITLE
(PUP-4757) added puppet-agent support for PE-only platforms

### PR DESCRIPTION
**Pull request by kevpl**
After speaking with @joshcooper, I realized that I was going down the wrong path with the `:peaio` rake task.  

This commit reverts that old work, and simply adds support for installing puppet-agent on PE-only platforms (using Beaker's `install_puppet_agent_dev_repo_on` method).

[skip ci]

### CODE REVIEW

**Comment by joshcooper** [comment]
#### sles-12
```
$ be rake ci:test:aio SHA=9bc81ceeac7971e61d76d9578bf50f1678490e45 CONFIG=config/nodes/sles-12-x86_64.yaml SUITE_VERSION=1.2.1.73.g9bc81ce
```

#### redhat-7
```
$ be rake ci:test:aio SHA=9bc81ceeac7971e61d76d9578bf50f1678490e45 CONFIG=config/nodes/redhat-7-x86_64.yaml SUITE_VERSION=1.2.1.73.g9bc81ce
```

#### ubuntu-14.04
```
$ be rake ci:test:aio SHA=9bc81ceeac7971e61d76d9578bf50f1678490e45 CONFIG=config/nodes/ubuntu-1404-x86_64.yaml SUITE_VERSION=1.2.1.73.g9bc81ce
```

#### ubuntu-10.04
```
$ be rake ci:test:aio SHA=9bc81ceeac7971e61d76d9578bf50f1678490e45 CONFIG=config/nodes/ubuntu-1004-x86_64.yaml SUITE_VERSION=1.2.1.73.g9bc81ce
```

#### win2012r2
```
$ be rake ci:test:aio SHA=9bc81ceeac7971e61d76d9578bf50f1678490e45 CONFIG=config/nodes/win2012r2-rubyx64.yaml SUITE_VERSION=1.2.1.73.g9bc81ce
```

**Comment by joshcooper** [comment]
Crap, I just realized this had PUP keywords. We really should be using HI tickets or (maint).

**Comment by kevpl** [comment]
sorry about that. I'll try to make sure to do this going forward.

**Comment by kylog** [comment]
Damn. I'll port my commit checker to hiera.

**Comment by kylog** [comment]
#282

**Pull request merged**
